
test_wl: test_wl.cpp 
	g++-11 test_wl.cpp ../src/system.cpp ../src/wl.cpp -o test_wl

test_fss: test_fss.cpp 
	g++-11 test_fss.cpp ../src/system.cpp ../src/fss_spinS.cpp ../src/fss.cpp -o test_fss

test_spins: test_spinS.cpp 
	g++-11 test_spinS.cpp ../src/system.cpp ../src/wl.cpp ../src/fss.cpp ../src/fss_spinS.cpp -o test_spins

