
test_wl: test_wl.cpp system.cpp system.h wl.h wl.cpp rng.h 
	g++-11 -fopenmp test_wl.cpp system.cpp wl.cpp -o test_wl

test_fss: test_fss.cpp system.cpp system.h fss.h fss.cpp rng.h 
	g++-11 -fopenmp test_ff.cpp system.cpp fss.cpp -o test_fss


